# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    name: adm
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    name: serv
    build: server/
    command: uvicorn main:app --reload
    ports:
      - 5000:8000