# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kSqHwjRhBOHIwU
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  adminer:
    container_name: adm
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    container_name: serv
    build: server/
    command: uvicorn main:app --reload
    ports:
      - 5000:8000


